// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhvvisuTAyHtJ_I-aEoz0gGMI2otdgYE',
    appId: '1:79100073535:web:2f82ca366cbe19b2cc8a8a',
    messagingSenderId: '79100073535',
    projectId: 'gogrocer-app-86dae',
    authDomain: 'gogrocer-app-86dae.firebaseapp.com',
    storageBucket: 'gogrocer-app-86dae.firebasestorage.app',
    measurementId: 'G-Q7BTH67JFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4vT9mdHD56wuQQ9X9cbfdhh4xrHbUVI',
    appId: '1:79100073535:android:541996a10ea179dbcc8a8a',
    messagingSenderId: '79100073535',
    projectId: 'gogrocer-app-86dae',
    storageBucket: 'gogrocer-app-86dae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWO_5QCnj1W57EE-htBMcpU_Kf9-UOboU',
    appId: '1:79100073535:ios:602cfc6327dac65bcc8a8a',
    messagingSenderId: '79100073535',
    projectId: 'gogrocer-app-86dae',
    storageBucket: 'gogrocer-app-86dae.firebasestorage.app',
    iosClientId: '79100073535-pdqm501h50gqkm3if5q2m02v8a8inpi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gogroceradmin.gogrocerAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWO_5QCnj1W57EE-htBMcpU_Kf9-UOboU',
    appId: '1:79100073535:ios:602cfc6327dac65bcc8a8a',
    messagingSenderId: '79100073535',
    projectId: 'gogrocer-app-86dae',
    storageBucket: 'gogrocer-app-86dae.firebasestorage.app',
    iosClientId: '79100073535-pdqm501h50gqkm3if5q2m02v8a8inpi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gogroceradmin.gogrocerAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnhvvisuTAyHtJ_I-aEoz0gGMI2otdgYE',
    appId: '1:79100073535:web:8c5745f7f0059584cc8a8a',
    messagingSenderId: '79100073535',
    projectId: 'gogrocer-app-86dae',
    authDomain: 'gogrocer-app-86dae.firebaseapp.com',
    storageBucket: 'gogrocer-app-86dae.firebasestorage.app',
    measurementId: 'G-LD996HFLF8',
  );
}
